excerpt_separator: ""
pygments: false
markdown: kramdown
url: http://ybbaigo.github.io
title: Seven Blue
tagline: ''
description: ''
paginate: 5
comments: true
google_analytics: UA-81592603-1
